lib/ex_aws/s3.ex

These changes fix a small problem with the typespec for get_object. Because the `|` operator for typespecs implies alternation and not cons, the effective typespec for the `opts` parameter was:
```elixir
[
{
:response, 
[
{:content_language, binary}
| {:expires, binary}
| {:cach_control, binary}
| {:content_disposition, binary}
| {:content_encoding, binary}
]
}
| [
{:encryption, customer_encryption_opts}
| {:range, binary}
| {:if_modified_since, binary}
| {:if_unmodified_since, binary}
| {:if_match, binary}
| {:if_none_match, binary}
]
]
```
This causes dialyzer to report errors if you try to pass the `:if_modified_since` option. With the changes on this PR, the typespec becomes the following, which matches the behavior of the function:
```elixir
[
{
:response, 
[
{:content_language, …
```

fix typespec for get_object_opts

---

lib/ex_aws/s3/upload.ex

op, including op.src, has to be copied to the new process spawned by Task.async_stream, and if op.src is "big enough" this can take a while and negates the performance wins from parallel execution.
* remove :src from op as it is not needed in the task
* use the (Module, :function, [args]) form, as &(...) creates a closure that captures all variables present in the scope (including the original op with :src)

fix performance issue in multipart upload

---

lib/ex_aws/s3/upload.ex

This bugfix should fix this issue: https://github.com/ex-aws/ex_aws/issues/567
The stream already uses `raw, binary`, and `read_ahead` options, so specifying those modes on stream causes the error on the latest versions of Erlang/Elixir.
**Tested environment**:
* Erlang/OTP 21.0
* Elixir 1.6.6
**Changes**:
* File streaming is not including modes now

Do not repeat file streaming modes as it causes errors in OTP 21.0

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

My use case was specifically to perform the `list_objects` operation leveraging S3 requester pays functionality.  This requires the inclusion of `x-amz-request-payer : requester` header.
Source: http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html
```
"After you configure a bucket to be a Requester Pays bucket, requesters must include x-amz-request-payer in their requests either in the header, for POST, GET and HEAD requests, or as a parameter in a REST request to show that they understand that they will be charged for the request and the data download."
```
I felt this was the least intrusive change to achieve the desired functionality.  A later conversation might be full blown support for this S3 feature in a separate GH issue.
Usage:
``` elixir …
```

Allow custom headers on list_objects requests

---

lib/ex_aws/s3/utils.ex

This allows us to set multiple tags as follows
ExAws.S3.put_object("bucket", "location", object, [{:tagging, "foo=bar"  }])

Hi Ben - a suggestion for support of S3 tags (x-amz-tagging)

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/download.ex

Add the ability to stream file contents directly to memory for performance reasons.
I need to add a test, but this I tested it manually and its working fine.

Add ability to stream download files directly into memory

---

lib/ex_aws/s3.ex

Hi there.
I got the following error on `ExAws.S3.put_bucket_cors/2` when using map in second argument.
```
** (BadMapError) expected a map, got: {:allowed_headers, ["*"]}
(elixir) lib/map.ex:451: Map.get({:allowed_headers, ["*"]}, :allowed_origins, [])
(ex_aws_s3) lib/ex_aws/s3/utils.ex:100: anonymous fn/2 in ExAws.S3.Utils.build_cors_rule/1
(elixir) lib/enum.ex:2994: Enum.flat_map_list/2
(ex_aws_s3) lib/ex_aws/s3/utils.ex:98: ExAws.S3.Utils.build_cors_rule/1
(elixir) lib/enum.ex:1340: anonymous fn/3 in Enum.map/2
(stdlib) maps.erl:232: :maps.fold_1/3
(elixir) lib/enum.ex:1964: Enum.map/2
(ex_aws_s3) lib/ex_aws/s3.ex:299: ExAws.S3.put_bucket_cors/2
```
But, when I use list of map, got a warning on dialyzer.
```
$ mix dialyzer
...
The function call will not succeed. …
```

Fix typespecs on put_bucket_cors/2

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

More info: https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html
Closes ex-aws/ex_aws_s3#40

Add support to s3 transfer acceleration on presigned urls

---

lib/ex_aws/s3/upload.ex

A multipart upload requires at least one part, otherwise the
CompleteMultipartUpload request fails with a MalformedXML error.
Let's avoid that by uploading an empty part when there are no parts.
Fixes #3.

Fix streaming upload of empty file

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

This is a proposed fix for issue https://github.com/ex-aws/ex_aws_s3/issues/77, where objects that have a `+` in the name aren't being escaped properly
It also requires PR https://github.com/ex-aws/ex_aws/pull/648 in the ex_aws repo as well

Ensure src_object is encoded for put_copy_object/5

---

lib/ex_aws/s3.ex

`:version_id` option key is used in the function body, but is not declared in the typespec. This leads to Dialyzer errors in any project that uses S3 and calls the funciton with this (valid) option. This PR fixes this by adding a `:version_id` option to the typespec.

Include :version_id option in typespec for head_object/3

---

lib/ex_aws/s3.ex

`presigned_url/5` accepts an optional list of headers which are passed through to ExAws.Auth. No breaking changes. Compatible with the latest ex_aws version (2.1.1).
Example:
```elixir
ExAws.S3.presigned_url(config, method, bucket, path, 
headers: [{"x-amz-acl", "public-read"}, {"Content-Type", type}]
)
```
Support headers used on browser-initiated file uploads that are not part of the query params.
Many of these are blocked waiting for analysis. Here is my take in the hopes it helps: 
* #39 - nearly identical, has merge conflicts
* #43 - same approach, no longer compatible with ex_aws master
* #36 - fixed by ex-aws/ex_aws#540 and this PR (see [comment](https://github.com/ex-aws/ex_aws/pull/540#issuecomment-433443943))
* ex-aws/ex_aws#602 - can be closed, done in ex-aws/ex_aws#540 and …

Pass through optional headers to presigned_url

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/utils.ex
test/lib/s3_test.exs

What?  
This PR adds the ability to fetch specific versions of object by adding a new `version_id` option to `S3.get_object/2`.
Why?
`ex_aws_s3` already allows you to list versions of an object with `S3.get_bucket_object_versions/1`, but there was no way to go and fetch objects based on a specific version.
What Else?
The parameter for the version id is `versionId`, which is `camelCase`.  It seems that most of the other parameters are `kebab-case`.  I found two other instances in the code where the `camelCase` key was being manually created, and switched them to also use the utility function.  If we liked it better the other way, let me know and I'll switch `get_object ` to do the same thing.

Add versionId for get_object

---

README.md

Some operations require XML parsing. When trying to call those functions (like `ExAws.S3.list_objects`) without `sweet_xml` as a dependency the app will report an error "Missing XML parser. Please see docs".
This change makes the dependency more obvious in the docs.
Primarily requesting this change because I was running into that error, was a bit confused, and only really understood the warning properly after I looked at the code and also saw https://github.com/ex-aws/ex_aws_s3/issues/32

Make Optional sweet_xml Dependency More Obvious

---

lib/ex_aws/s3.ex

I like grabbing a drink down at the pub as much as the next person, but this is a `put_object` rather than the `pub_object` ;)
Also -> these files are very much out of line with the standard formatting  ... should we consider doing something about that? It's a bit painful with a text editor set up to reformat on save ... :/

pub_object -> put_object

---

lib/ex_aws/s3/upload.ex

The call to `Enum.map/2` below will execute the stream and will avoid an extra list traversal.

Upload.perform/2: Remove redundant Enum.to_list/1 call

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

Object keys in `delete_multiple_objects/3` were being used exactly as passed. However, [AWS provides a list of special characters that need to be escaped](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-xml-related-constraints).
Fixes #85.

Escape XML keys in delete_multiple_objects/3

---

lib/ex_aws/s3.ex

Our dialyzer checks started throwing errors on `ex_aws_s3` when we upgraded from 2.1.0 to 2.2.0.
```
The function call will not succeed.
ExAws.S3.upload(
%File.Stream{
:line_or_bytes => _,
:modes => maybe_improper_list(),
:path => _,
:raw => boolean()
},
_bucket :: any(),
_upload_path :: binary(),
_upload_opts :: [{:acl, :public_read}, ...]
)
breaks the contract
(
source :: Enumerable.t(),
bucket :: String.t(),
path :: String.t(),
opts :: upload_opts()
) :: ExAws.S3.Upload.t()
```
It looks like the typespecs for `upload_opts` were inadvertently combining the inner type of `{:key, value}` with the outer type `[{:key, value}]` leading to invalid typespecs. It's trying to force us to pass options in like:
```elixir
upload_opts = [
{:max_concurrency, 1},
[
{:cache_control, …
```

Fix typespecs so upload_opts are defined correctly

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/upload.ex
test/lib/s3_test.exs
test/support/file_helpers.ex

This PR adds the ability to delete an object version in the S3 versioning enabled storage.
Add `:version_id` option to `delete_object/3` function.
The API Document is [here](https://docs.aws.amazon.com/AmazonS3/latest/API/API_DeleteObject.html). (delete_object)

Add version_id options to delete_object function.

---

lib/ex_aws/s3/utils.ex
test/lib/s3_test.exs

Adds support for the `x-amz-tagging-directive` header which is required for the `CopyObject` action when supplying the `x-amz-tagging` header (which is currently supported).
From the [CopyObject](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html) documentation:
```
x-amz-tagging
The tag-set for the object destination object this value must be used in conjunction with the TaggingDirective.
```
Example usage:
```elixir
ExAws.S3.put_object_copy(
dest_bucket,
dest_key,
src_bucket,
src_key,
tagging: "tag1=foo&tag2=bar",
tagging_directive: :REPLACE
)
%ExAws.Operation.S3{
#...
headers: %{
"x-amz-copy-source" => "bucket/key",
"x-amz-tagging" => "tag1=foo&tag2=bar",
"x-amz-tagging-directive" => :REPLACE
},
#...
}
```

Support tagging_directive in ExAws.S3.Utils.put_object_headers/1

---

README.md
lib/ex_aws/s3.ex
test/lib/s3_test.exs

The following PR will allow us to create signed url in the following nomenclature: `https://custom.domain.com/image.jpg?` which wasn't feasible before with this library. This allow us to be independent of amazon host. As in real time scenario when generating signed url for clients side application the IP whitelisting is a well known problem. Certainly this resolve the prior issue as one get better control over custom domain IPs. 
Further benefits with been custom domain as host - provision us to configure authentication layer on access of `presigned` url too.
Inspired from the following issues:
- https://github.com/aws/aws-sdk-js/issues/891
- https://github.com/ex-aws/ex_aws_s3/issues/154

Adding `bucket_as_host` flag to generate signed url

---

lib/ex_aws/s3.ex

Update the example for using `download_file` to create a
line-orientented stream, conforming to the code used in nimble_csv which
accounts for a multi-line final chunk. I tested this code in my project and it worked as expected there.
Thanks to @LostKobrakai for writing (and pointing out) his very useful work!
Closes https://github.com/ex-aws/ex_aws_s3/issues/169

Update example for streaming lines

---

lib/ex_aws/s3/utils.ex
test/lib/s3/utils_test.exs

The S3 docs mention the format for unversioned buckets [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html#lifecycle-config-conceptual-ex5).
Notably when the Expiration rule doesn't have a ExpiredObjectDeleteMarker tag which is how it is in our code. This fixed it. Please let me know if there's anything else it needs.

Support updating lifecycles for non-versioned buckets

---

lib/ex_aws/s3.ex

`"""` doesn't escape the `\n` on line 692:
but `~S"""` does:

Switch to sigil_S for doc that contains newline

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/lazy.ex

There is a bug when you stream `list_objects_v2` that it falls back to use v1 request. As a result some of v2 parameters are not properly recognised. 
This fix creates a new streaming function for v2 and utilises `continuation_token` to fetch the next batch.

list_objects_v2 to use dedicated streaming function

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

www form is not supported by minio. The AWS docs mention 
> …need to be URL encoded or referenced as HEX.
https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html
So `%20` should work for spaces.

Use percent encoding instead of www form for header

---

lib/ex_aws/s3.ex

`presigned_post/4` takes a keyword list as the opts argument however the typespec is wrong for the case of `content_length_range`,
which is defined as a 3-element tuple, this is wrong and the rest of the code expects a 2-element tuple where the second one is a 2-element integer list
[tests ref](https://github.com/ex-aws/ex_aws_s3/blob/6b375da2a1912d16f80e88860cbc9c74989588a9/test/lib/s3_test.exs#L587) and the [implementation ref](https://github.com/ex-aws/ex_aws_s3/blob/14244d8ecb4e5766509a23b1296f5c013d1382c5/lib/ex_aws/s3/utils.ex#L309) 
This causes dialyzer warnings when using the `content_length_range` param, this PR should fix the problem

fix wrong presigned_post_opts typespec

---

lib/ex_aws/s3/download.ex

Problem: 
- currently it is hard to understand, what actually went wrong during a failed download
Solution: 
- return also the captured error in the rescue clause of try … rescue statement

Feat: Capture the actual error message for downloading

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/utils.ex
test/lib/s3_test.exs

I updated the `x-amz-storage-class` header to more-formally support the storage classes Amazon has listed [here](https://docs.aws.amazon.com/AmazonS3/latest/userguide/storage-class-intro.html).
The following screenshot is taken from Amazon's [PutObject documentation](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html).
To do this I needed to slightly alter some default behavior. The typespecs for storage class originally showed acceptable values of `:standard` and `:reduced_redundancy`. I expanded those to include lowercase, atomized versions of the storage classes listed above. The test for storage class showed that a string was acceptable as well. Strings are still acceptable but now they will be upcased. Atoms will be stringified and upcased.

Update storage class types

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/parsers.ex
test/lib/s3/parser_test.exs
test/lib/s3/upload_test.exs
test/lib/s3_test.exs

Trying to revive #106, which seemed to have gone dormant. The current implementation of `upload_part_copy` does not seem to work at all, and this fixes it.
This is a slightly different take. Like `S3.upload_part`, the upload_id, the part number, and the range are required attributes and shouldn't be put into opts, but part of the explicit API. Other than that, I copied the code mostly verbatim from #106 and just ensured it merged cleanly.

Multipart copy requires upload id, part number, and source range

---

lib/ex_aws/s3.ex

Allow the presigned_url option "start_datetime" to accept Elixir style dates (DateTime and NaiveDateTime), in addition to the original Erlang style :calendar.datetime().

Allow Elixir date types for start_datetime

---

lib/ex_aws/s3/parsers.ex
test/lib/s3/parser_test.exs

Realized we were missing a fall-through for when pattern matching failed on this parser.

Need to handle error cases for parse_upload_part_copy

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

The PR leaves
- MD5 as default, so existing code and users of this library would not be affected.
Introduces 
- the configuration `content_hash_algorithm` under `ex_aws_s3`.
As a result, the library `ex_aws_s3` could use other encryption algorithms other than MD5 which is not FIPS compliant. So may be necessary for some to be able to set the hashing algorithm used.

Avoid using hardcoded MD5 when calculating hash of content.

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/upload.ex

Adds the option `:refetch_auth_on_request` to `ExAws.S3.upload/4`. This will re-fetch the auth from the library config on each request in the upload process instead of using the initial auth. 
Fixes an edge case uploading large files when using a strategy from `ex_aws_sts` that provides short lived tokens, where uploads could fail if the token expires before the upload is completed. Defaults to `false`.
If using [`ex_aws_sts`](https://github.com/ex-aws/ex_aws_sts), short authentication tokens are generated and cached according to the config. However, they are only fetched **once** from the auth cache when this call is made.
```elixir
file
|> ExAws.S3.upload_file()
|> ExAws.S3.upload("bucket_foo", "object_id")
|> ExAws.request()
```
There are three requests that need authentication in …

Add option to get auth from AuthCache on every request when uploading  to S3 in a stream

---

README.md
lib/ex_aws/s3.ex
test/lib/s3_test.exs

While it was possible to specify an alternate hashing algorithm to ex_aws_s3, the header wasn't correctly appended to the request and was instead appended as `Content-<hash algo>`. AWS looks to require either `Content-MD5` or `x-amz-checksum-<hash algo>` so this implements that behavior.
I also added some unit tests around this. Open to suggestions as to how to improve them since I was a little unsure about modifying the application env during a test.

Append x-amz-checksum headers when using hashing algorithm other than MD5

---

lib/ex_aws/s3.ex

Clarify that presigned URLs are generated locally.
I need to generate multiple of these for a page load. Initially I assumed that this operation had to contact AWS and was looking for a way to request a batch of presigned URLs. But having experimented and looked at the code, I see that this is a local operation, so I can just map over the objects. I thought that was worth noting in the docs.

Clarify that presigned URLs are generated locally

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/utils.ex
test/lib/s3/utils_test.exs

Adds NewerNoncurrentVersions to put lifecycle configuration

feat: add newer_concurrent_versions option to put lifecycle

---

lib/ex_aws/s3/parsers.ex
test/lib/s3/parser_test.exs

Similar to: https://github.com/ex-aws/ex_aws_s3/pull/226
The goal is avoid crashing on `NoSuchUpload` when calling `ExAws.S3.complete_multipart_upload` with an already completed ID, aborted ID etc, before:
```elixir
** (FunctionClauseError) no function clause matching in ExAws.S3.Parsers.parse_complete_multipart_upload/1
The following arguments were given to ExAws.S3.Parsers.parse_complete_multipart_upload/1:
{:error, {:http_error, 404, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>NoSuchUpload</Code><Message>The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.</Message><Key>533d0266-ce72-4bc5-b6b0-79157531fc3c</Key><BucketName>test</BucketName><Resource>/test/533d0266-ce72-4bc5-b6b0-79157531fc3c< …
```

Handle errors in parse_complete_multipart_upload

---

lib/ex_aws/s3.ex
test/lib/s3_test.exs

Add checks for nil and empty string in delete_object. Calling the function with empty values results in an S3 operation that would try to delete the bucket itself.

Add empty value checks for delete_object

---

lib/ex_aws/s3/download.ex

We are using `:ex_aws_s3` package in a project with `:req` as a client adapter, and we were experiencing an error because the logic to obtain the content size from the response headers assumes that the header is a `binary`. However, `:req` uses a list of strings as a type.
This PR adjusts the code to handle both cases gracefully. Please, let me know if you'd like me to add an integration test where `:req` is used as an adapter.

fix: stream! when the client adapter models response headers as lists

---

lib/ex_aws/s3.ex

Hi!
I noticed that there was a small warning when compiling this project so I went ahead and fixed it. Let me know if this should match on an actual step instead.

Fix warning for deprecated match

---

.github/workflows/on-push.yml
test/support/file_helpers.ex

List of changes:
- resolve type warnings in test case
- use specific versions by string instead of number in CI matrix, see https://github.com/erlef/setup-beam?tab=readme-ov-file#specify-versions-as-strings-not-numbers

Support Elixir 1.18 in GitHub CI

---

README.md

Hello, ExAws team!
Thanks for your work on these projects. So, this PR enables some syntax highlighting for the examples present in the README.md. It's a small thing, but I think it's much easier to recognize the Elixir syntax if it's correctly syntax-highlighted.

Set the Elixir language on examples in README.md

---

lib/ex_aws/s3.ex
lib/ex_aws/s3/parsers.ex
test/lib/s3/parser_test.exs

Align naming with official S3 clients ([cli](https://docs.aws.amazon.com/cli/latest/reference/s3api/#cli-aws-s3api), [python](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_object_versions.html), [js](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/Package/-aws-sdk-client-s3/Interface/ListObjectVersionsRequest/)).
This makes the `ExAws.S3` function easier to find.

Rename get_bucket_object_versions to list_object_versions
